name: cincinnati-insurance-training
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.10
    - ipykernel>=6.0
    - pip>=22.1
    - nbconvert>=7.0
    - numpy>=1.24
    - pandas>=1.5
    - matplotlib>=3.6
    - seaborn>=0.12
    - ipykernel>=6.20
    - notebook>=6.0
